version: '3.9'

services:
  app1:
    build: .
    ports:
      - "3000:5000"
    depends_on:
      db:
        condition: service_healthy
  app2:
    build: .
    ports:
      - "3001:5000"
    depends_on:
      db:
        condition: service_healthy
  app3:
    build: .
    ports:
      - "3002:5000"
    depends_on:
      db:
        condition: service_healthy
  lb:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - './default.conf:/etc/nginx/conf.d/default.conf'

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "chatapp"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    
