version: '3.9'

services:
  app:
    build: .
    ports:
      - "80:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "chatapp"
    healthcheck:
      test: ["CMD", "mysqladmin","ping","-h","localhost"]
      timeout: 20s
      retries: 10
      start_period: 30s
    
